<#
.SYNOPSIS
    Packages Syndicate IMS for the JCWebsite shared host (DirectAdmin, no SSH)
    at synidcatesupply.store. The spelling of the domain is intentional.

.DESCRIPTION
    The host serves domains/synidcatesupply.store/public_html and offers no
    terminal, so nothing can be built or run there. Everything is prepared
    here and uploaded through File Manager + phpMyAdmin.

    Output, in -Destination:
      synidcatesupply.tar.gz  -- extract inside domains/synidcatesupply.store/
        syndicate-ims/   the app, OUTSIDE the web root (so .env, vendor/,
                         storage/ can never be fetched by URL)
        public_html/     the contents of public/, with an index.php that
                         points at ../syndicate-ims and rebinds public_path()
                         to itself -- uploads, part images and the Vite
                         manifest all resolve against public_html
      database.sql     -- import with phpMyAdmin

    tar.gz, never Compress-Archive: Windows zips store backslash paths, which
    a Linux extractor turns into broken directory names (learned on the old
    Hostinger deploy).

    The .env is generated from the local one (mail settings carry over) with
    production values and a fresh APP_KEY. DB_PASSWORD comes from
    -DbPassword, or is left as a placeholder to type in on the host with
    File Manager's editor.

    File is ASCII-only: PowerShell 5.1 reads a BOM-less .ps1 as ANSI.

.EXAMPLE
    ./deploy/package-for-hosting.ps1 -DbName synidcat_shop -DbUser synidcat_shop
    ./deploy/package-for-hosting.ps1 -DbName x -DbUser y -SkipDatabase
#>

param(
    [Parameter(Mandatory = $true)][string]$DbName,
    [Parameter(Mandatory = $true)][string]$DbUser,
    # Optional. Left out, .env gets a placeholder to type in on the host.
    [string]$DbPassword = 'TYPE_THE_DATABASE_PASSWORD_HERE',
    # GetFolderPath, not $env:USERPROFILE\Desktop: with OneDrive backup on,
    # the Desktop people actually see is OneDrive\Desktop.
    [string]$Destination = (Join-Path ([Environment]::GetFolderPath('Desktop')) 'syndicate-hosting'),
    [string]$AppUrl = 'https://synidcatesupply.store',
    # Code-only update: no database.sql, so a re-import can't clobber live orders.
    [switch]$SkipDatabase,
    # Which local database becomes database.sql. syndicate_demo = the
    # simulated store history (see DemoOrdersSeeder).
    [string]$SourceDb = 'syndicate_ims'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot

function Step($m) { Write-Host "`n=== $m ===" -ForegroundColor Cyan }
function Die($m)  { Write-Host "`n  X $m`n" -ForegroundColor Red; exit 1 }

Step 'Checking the build'
if (-not (Test-Path "$root\public\build\manifest.json")) { Die 'public/build is missing. Run: npm.cmd run build' }
if (Test-Path "$root\public\hot") { Die 'public/hot exists (Vite dev server). Stop npm run dev, delete public\hot, then npm.cmd run build.' }

$staging = Join-Path $Destination 'staging'
if (Test-Path $Destination) { Remove-Item $Destination -Recurse -Force }
New-Item -ItemType Directory -Path "$staging\syndicate-ims", "$staging\public_html" -Force | Out-Null

Step 'Copying the app (outside the web root)'
$app = @('app', 'bootstrap', 'config', 'database', 'lang', 'resources', 'routes', 'storage', 'vendor',
         'artisan', 'composer.json', 'composer.lock')
foreach ($item in $app) {
    $src = Join-Path $root $item
    if (Test-Path $src) { Copy-Item $src -Destination "$staging\syndicate-ims" -Recurse -Force; Write-Host "  + $item" }
}

Step 'Copying public/ into public_html'
# public/files holds the client's ORIGINAL photos -- source material for the
# image pipeline, never served by the site. 30 MB of upload for nothing.
Get-ChildItem "$root\public" -Force | Where-Object { $_.Name -notin @('files', 'hot') } |
    ForEach-Object { Copy-Item $_.FullName -Destination "$staging\public_html" -Recurse -Force; Write-Host "  + $($_.Name)" }

Set-Content -Path "$staging\public_html\index.php" -Encoding ascii -Value @'
<?php

// Generated by deploy/package-for-hosting.ps1. The app lives one level up in
// ../syndicate-ims so nothing but this folder is reachable by URL.

use Illuminate\Contracts\Http\Kernel;
use Illuminate\Http\Request;

define('LARAVEL_START', microtime(true));

$appRoot = __DIR__.'/../syndicate-ims';

if (file_exists($maintenance = $appRoot.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

require $appRoot.'/vendor/autoload.php';

$app = require_once $appRoot.'/bootstrap/app.php';

// public_path() must mean THIS folder: product photo uploads, /parts images
// and the Vite manifest are all looked up through it.
$app->instance('path.public', __DIR__);

$kernel = $app->make(Kernel::class);

$response = $kernel->handle(
    $request = Request::capture()
)->send();

$kernel->terminate($request, $response);
'@

Step 'Writing the production .env'
$envLines = Get-Content "$root\.env"
$key = (& php "$root\artisan" key:generate --show).Trim()
$overrides = [ordered]@{
    APP_ENV = 'production'; APP_DEBUG = 'false'; APP_URL = $AppUrl; APP_KEY = $key
    LOG_LEVEL = 'error'
    DB_HOST = 'localhost'; DB_PORT = '3306'; DB_DATABASE = $DbName; DB_USERNAME = $DbUser
    DB_PASSWORD = $DbPassword
}
$out = foreach ($line in $envLines) {
    if ($line -match '^([A-Z0-9_]+)=' -and $overrides.Contains($Matches[1])) { "$($Matches[1])=$($overrides[$Matches[1]])" }
    else { $line }
}
Set-Content -Path "$staging\syndicate-ims\.env" -Value $out -Encoding ascii

Step 'Clearing logs, sessions and caches'
foreach ($dir in 'storage\logs', 'storage\framework\cache\data', 'storage\framework\sessions', 'storage\framework\views', 'bootstrap\cache') {
    $p = "$staging\syndicate-ims\$dir"
    if (Test-Path $p) { Get-ChildItem $p -Force | Where-Object { $_.Name -ne '.gitignore' } | Remove-Item -Recurse -Force }
    New-Item -ItemType Directory -Path $p -Force | Out-Null
}

if (-not $SkipDatabase) {
    Step 'Exporting the database'
    $dump = 'C:\xampp\mysql\bin\mysqldump.exe'
    if (-not (Test-Path $dump)) { Die "mysqldump not found at $dump" }
    # --result-file, not >: PowerShell 5.1's > writes UTF-16, which phpMyAdmin rejects.
    & $dump -u root --single-transaction --skip-comments --result-file="$Destination\database.sql" $SourceDb
    if ($LASTEXITCODE -ne 0) { Die 'mysqldump failed. Is MySQL running in XAMPP?' }
}

Step 'Compressing'
& tar.exe -czf "$Destination\synidcatesupply.tar.gz" -C $staging syndicate-ims public_html
if ($LASTEXITCODE -ne 0) { Die 'tar failed' }
Remove-Item $staging -Recurse -Force

Get-ChildItem $Destination | ForEach-Object { '{0,-26} {1,8:N1} MB' -f $_.Name, ($_.Length / 1MB) }
Write-Host "`nDone: $Destination" -ForegroundColor Green
